version: '2.2'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pageknocks
      MYSQL_DATABASE: pageknocks
      MYSQL_USER: pageknocks
      MYSQL_PASSWORD: pageknocks
    volumes:
        - data:/var/lib/mysql
    healthcheck:
      test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
      timeout: 20s
      retries: 10

  mitm_proxy:
    build:
      context: containers_path
      dockerfile: mitm_Dockerfile_path
    restart: always
    ports:
    - ${PROXY_PORT}:8080
    environment:
      PROXY_ADDRESS: ${PROXY_ADDRESS}
      PROXY_PORT: ${HTTP_PORT}
      KNOCKS: ${KNOCKS}
      DEFAULT_KNOCKING_SEQUENCE: /app/data/knocking_sequence.csv
      ADMIN_DEF_KNOCKING_SEQUENCE: /app/data/admin_knock_sequence.txt
      SITEMAP: /app/data/pre_authentication_urls_wordpress.txt
      CONFIG_FILE: /app/conf/wordpress-conf.json
    depends_on:
      db:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    # depends_on:
    #   db:
    #       condition: service_healthy
    ports:
      - 14082:80
    environment:
      MYSQL_ROOT_PASSWORD: Fm2p6!$m6aoy
      MYSQL_USERNAME: pageknocks
      PMA_HOST: db

  creation_api:
    build: 
      context: containers_path
      dockerfile: creation_Dockerfile_path
    ports:
      - 14081:5000
    environment:
      FLASK_ENV: development
      CONFIG_FILE: /app/conf/wordpress-conf.json
    depends_on:
      db:
        condition: service_healthy

  honeypot_webapp_db:
    # image: mysql:5.7
    # restart: always
    # environment:
    #   MYSQL_ROOT_PASSWORD: pageknocks
    #   MYSQL_DATABASE: pageknocks
    #   MYSQL_USER: pageknocks
    #   MYSQL_PASSWORD: pageknocks
    # volumes:
    #     - data:/var/lib/mysql
    # healthcheck:
    #   test: ["CMD", 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p$$MYSQL_ROOT_PASSWORD' ]
    #   timeout: 20s
    #   retries: 10
    image: web_application_db_image
    restart: always
    
  honeypot_webapp:
    environment:
      WORDPRESS_DB_HOST: honeypot_webapp_db
    depends_on:
      - honeypot_webapp_db
    image: web_application_image
    ports:
      - ${HTTP_PORT}:80
    restart: always

volumes:
  data:
